services:
  web:
    image: nginx:latest
    working_dir: /app
    ports:
      - "8081:80"
      - "8082:443"
    depends_on:
      - python
    volumes:
      - "./docker/files/static/502.html:/app/502.html:cached"
      - "./docker/files/config/nginx.conf.template:/etc/nginx/templates/default.conf.template:cached"
      - "./docker/files/certs:/etc/nginx/certs"
      - "./src/media:/app/media"
      - "./src/static:/app/static"
    environment:
      - PYTHON_HOST=http://python
      - MEDIA_REMOTE_DOMAIN=example.com

  python:
    image: frojd/company_project_python
    build:
      context: ./src
      args:
        - ENVIRONMENT=local
    # Modify command to allow overriding via docker-compose run
    entrypoint: ["./docker-entrypoint.sh"]
    command: "runserver"
    volumes:
      - "./src:/home/app/web"
      - "./src/media:/home/app/media"
      - "./src/static:/home/app/static"
      - "./src/coverage:/home/app/coverage"  # Add coverage volume
    depends_on:
      - db
    env_file: ./docker/config/python.env
    environment:
      - PYTHONPATH=/home/app/web
      - DJANGO_SETTINGS_MODULE=teki.settings.test  # For testing

  db:
    image: postgis/postgis:12-2.5-alpine
    ports:
      - "8083:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
      - "./docker/files/shared:/shared:rw"
      - "savima_db_data:/var/lib/postgresql/data"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app

volumes:
  savima_db_data:  # Define the volume here
