from main.tasks import Task
from main.pages.battle import BattlePage, BattleTaskInstance
from wagtail.models import Page
from main.models import TerrainType
import random

# Create 10 tasks
difficulties = ['easy', 'medium', 'hard']
tasks = []
for i in range(10):
    task = Task.objects.create(
        title=f"Task {i+1}",
        description="Autogenerated task",
        point_value=(i % 4) + 1,
        difficulty=random.choice(difficulties)
    )
    tasks.append(task)

# Fetch terrain options by name
terrains = {
    "mountain": TerrainType.objects.get(name__iexact="mountain"),
    "desert": TerrainType.objects.get(name__iexact="desert"),
    "glacier": TerrainType.objects.get(name__iexact="glacier"),
}
terrain_list = list(terrains.values())

# Choose a parent page to attach BattlePages under (replace slug or ID accordingly)
parent = Page.objects.get(slug='home')  # Or use ID

# Create 12 BattlePages and link 3 tasks to each
for i in range(12):
    battle_page = BattlePage(
        title=f"Battle Page {i+1}",
        description="Autogenerated battle",
        point_value=random.randint(1, 4),
        recommended_frequency=1,
        terrain=terrain_list[i % 3],
        path_type='straight',
        bg_color="#ffffff",
        bg_color2="#eeeeee",
    )
    parent.add_child(instance=battle_page)
    battle_page.save_revision().publish()

    # Link 3 tasks
    for j in range(3):
        task = tasks[(i + j) % len(tasks)]
        BattleTaskInstance.objects.create(
            task=task,
            battle_page=battle_page,
            status='available'
        )
