[tool.ruff]
line-length = 88

# Never enforce `E501` (line length violations).
ignore = ["E501"]

exclude = [
    "venv",
    "*/migrations/*",
    "node_modules",
]

[tool.ruff.per-file-ignores]
"teki/settings/local.py" = ["F405", "F403"]
"teki/settings/test.py" = ["F405", "F403"]
"teki/settings/stage.py" = ["F405", "F403"]
"teki/settings/prod.py" = ["F405", "F403"]
