# Generated by Django 5.0.7 on 2025-04-14 09:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battlepage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="battlepage",
            name="point_value",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="battlepage",
            name="recommended_frequency",
            field=models.PositiveIntegerField(
                blank=True, help_text="Recommended times per day"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
    ]
