# Generated by Django 5.0.7 on 2025-04-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_battlepage_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="intro",
        ),
    ]
