# Generated by Django 5.0.7 on 2025-04-14 12:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_home_page_remove_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battlepage",
            name="description",
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="battlepage",
            name="point_value",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="battlepage",
            name="recommended_frequency",
            field=models.PositiveIntegerField(
                help_text="Recommended times per day", null=True
            ),
        ),
    ]
