# Generated by Django 5.0.7 on 2025-04-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_battlepage_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battlepage",
            name="bg_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
