# Generated by Django 5.0.7 on 2025-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_battlepage_bg_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="battlepage",
            name="bg_color2",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
