# Generated by Django 5.0.7 on 2025-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_battlepage_bg_color2"),
    ]

    operations = [
        migrations.AddField(
            model_name="battlepage",
            name="path_type",
            field=models.CharField(
                choices=[
                    ("straight", "Straight"),
                    ("bumpy", "Bumpy"),
                    ("zigzag", "Zigzag"),
                    ("curvy", "Curvy"),
                ],
                default="straight",
                help_text="Visual style of the battle path.",
                max_length=10,
            ),
        ),
    ]
