# Generated by Django 5.0.7 on 2025-04-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_battlepage_path_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathposition",
            name="terrain",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="current_position",
        ),
        migrations.DeleteModel(
            name="BattlefieldPathPosition",
        ),
        migrations.DeleteModel(
            name="PathPosition",
        ),
    ]
