# Generated by Django 5.0.7 on 2025-04-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_pathposition_terrain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battlepage",
            name="battlefield",
        ),
        migrations.DeleteModel(
            name="Battlefield",
        ),
    ]
