# Generated by Django 5.0.7 on 2025-04-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_battlepage_battlefield_delete_battlefield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battlepageprogress",
            name="page",
        ),
        migrations.RemoveField(
            model_name="battlepageprogress",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="battlepagesupportmessage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="battlepagesupportmessage",
            name="support_message",
        ),
        migrations.DeleteModel(
            name="BattlePageAchievement",
        ),
        migrations.DeleteModel(
            name="BattlePageProgress",
        ),
        migrations.DeleteModel(
            name="BattlePageSupportMessage",
        ),
    ]
