# Generated by Django 5.0.7 on 2025-04-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="battlepage",
            name="terrain",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the terrain type for this battle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="battle_pages",
                to="main.terraintype",
            ),
        ),
    ]
