# Generated by Django 5.0.7 on 2025-04-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_remove_battlepagetask_assigned_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertask",
            name="battle_page",
        ),
        migrations.RemoveField(
            model_name="usertask",
            name="task",
        ),
        migrations.AddField(
            model_name="usertask",
            name="battle_page_task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="main.battlepagetask",
            ),
            preserve_default=False,
        ),
    ]
