# Generated by Django 5.0.7 on 2025-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_usertask_battle_page_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
