# Generated by Django 5.0.7 on 2025-04-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_progress_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BattlePageTask",
            new_name="BattleTaskPage",
        ),
    ]
