# Generated by Django 5.0.7 on 2025-04-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_dashboardpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardPage",
        ),
    ]
