# Generated by Django 5.0.7 on 2025-05-02 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_rename_usertask_taskinstance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinstance",
            name="battle_task_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_instances",
                to="main.battletaskpage",
            ),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="assigned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="battle_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_instances",
                to="main.battlepage",
            ),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("assigned", "Assigned"),
                    ("completed", "Completed"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="main.task",
            ),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskinstance",
            unique_together={("task", "battle_page")},
        ),
    ]
