# Generated by Django 5.0.7 on 2025-05-04 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_battletaskpage_active_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battlepage",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="battlepage",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="active_from",
        ),
        migrations.RemoveField(
            model_name="task",
            name="active_until",
        ),
        migrations.RemoveField(
            model_name="task",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="task",
            name="repeat_daily",
        ),
        migrations.RemoveField(
            model_name="task",
            name="repeat_weekly",
        ),
        migrations.AddField(
            model_name="battletaskpage",
            name="active_from",
            field=models.DateField(
                blank=True, help_text="Date when this task becomes available", null=True
            ),
        ),
        migrations.AddField(
            model_name="battletaskpage",
            name="active_until",
            field=models.DateField(
                blank=True,
                help_text="Date when this task is no longer available",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battletaskpage",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                help_text="If weekly, which day it should be available",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battletaskpage",
            name="repeat_daily",
            field=models.BooleanField(
                default=False, help_text="Whether this task repeats daily"
            ),
        ),
        migrations.AddField(
            model_name="battletaskpage",
            name="repeat_weekly",
            field=models.BooleanField(
                default=False, help_text="Whether this task repeats weekly"
            ),
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "battle_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tasks",
                        to="main.battlepage",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="main.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TaskInstance",
        ),
    ]
