# Generated by Django 5.0.7 on 2025-05-04 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_remove_battlepage_end_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertask",
            name="battle_page",
        ),
        migrations.RemoveField(
            model_name="usertask",
            name="task",
        ),
        migrations.RemoveField(
            model_name="usertask",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usertask",
            name="validated_by",
        ),
        migrations.AddField(
            model_name="task",
            name="active_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="active_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_daily",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_weekly",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BattleTaskInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("repeat_at_hour", models.PositiveIntegerField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("assigned_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "battle_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_tasks",
                        to="main.battlepage",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_tasks",
                        to="main.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battle_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_battle_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BattleTaskPage",
        ),
        migrations.DeleteModel(
            name="UserTask",
        ),
    ]
