# Generated by Django 5.0.7 on 2025-05-04 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_remove_usertask_battle_page_remove_usertask_task_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="battletaskinstance",
            name="battle_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_instances",
                to="main.battlepage",
            ),
        ),
        migrations.AlterField(
            model_name="battletaskinstance",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_instances",
                to="main.task",
            ),
        ),
        migrations.AlterField(
            model_name="battletaskinstance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="battletaskinstance",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_task_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
