# Generated by Django 5.0.7 on 2025-05-04 02:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_battletaskinstance_battle_page_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="battletaskinstance",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="battletaskinstance",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="battletaskinstance",
            name="battle_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_instances",
                to="main.battlepage",
            ),
        ),
    ]
