# Generated by Django 5.0.7 on 2025-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_battletaskinstance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battlepage",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battlepage",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
