# Generated by Django 5.0.7 on 2025-05-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_task_est_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="est_time",
        ),
    ]
