# Generated by Django 5.0.7 on 2025-05-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_remove_task_est_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="est_time",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
